### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zzh1996** [huiyiqun/zaobot#7]
建议增加这个功能：查看自己的历史睡眠记录和统计信息

**Comment by huiyiqun** [comment]
因为计划重写，暂时不准备加feature。

**Comment by zzh1996** [comment]
话说这个项目重写了吗

**Comment by huiyiqun** [comment]
没有…应该没有时间来重写了

2018年11月13日 上午1:17，"Zihan Zheng" <notifications@github.com>写道：

话说这个项目重写了吗

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/huiyiqun/zaobot/issues/7#issuecomment-437950647>, or mute
the thread
